# headers and icon 
title: hannah estes
info: phd cs @ nc state
icon-pic: assets/img/comic_portrait_square.png

# exclude these items when generated website in _site/index.html
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
